# Generated by Django 5.2.7 on 2025-10-30 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisasjon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fylke', models.CharField(max_length=100, verbose_name='Fylke')),
                ('kommune', models.CharField(max_length=100, verbose_name='Kommune')),
                ('organisasjon', models.CharField(max_length=200, unique=True, verbose_name='Organisasjonsnavn')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('nettside', models.URLField(blank=True, null=True, verbose_name='Nettside')),
                ('epost', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-post')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('status', models.CharField(choices=[('Aktiv', 'Aktiv'), ('Ukjent', 'Ukjent'), ('Passiv', 'Passiv')], default='Ukjent', max_length=10, verbose_name='Status')),
                ('kilde', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kilde')),
                ('opprettet', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opprettet')),
                ('sist_endret', models.DateTimeField(auto_now=True, verbose_name='Sist endret')),
            ],
            options={
                'verbose_name_plural': 'Organisasjoner',
                'ordering': ['organisasjon'],
            },
        ),
    ]
