# Generated by Django 5.2.7 on 2025-10-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisasjon',
            name='breddegrad',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breddegrad (Latitude)'),
        ),
        migrations.AddField(
            model_name='organisasjon',
            name='lengdegrad',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Lengdegrad (Longitude)'),
        ),
    ]
