# Generated by Django 5.2.7 on 2025-10-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0002_organisasjon_breddegrad_organisasjon_lengdegrad'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisasjon',
            name='lenke_status',
            field=models.CharField(choices=[('OK', 'OK'), ('FEIL', 'FEIL'), ('UKJENT', 'UKJENT')], default='UKJENT', max_length=10, verbose_name='Lenkestatus'),
        ),
    ]
