# Generated by Django 5.2.7 on 2025-12-08 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0003_organisasjon_lenke_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokallag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aktivitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=200)),
                ('dato', models.DateField(help_text='Dato for aktiviteten')),
                ('kortinfo', models.CharField(help_text="Kort tekst (3–5 linjer) som vises under 'Fra lagene'", max_length=300)),
                ('beskrivelse', models.TextField(help_text='Full beskrivelse av aktiviteten som vises på aktivitetssiden')),
                ('sted', models.CharField(blank=True, help_text='Valgfritt: Sted for aktiviteten', max_length=200)),
                ('slug', models.SlugField(help_text='Brukes i URL for aktivitetssiden', max_length=220)),
                ('publisert', models.BooleanField(default=True, help_text='Hvis denne er av, vises ikke aktiviteten offentlig')),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('oppdatert', models.DateTimeField(auto_now=True)),
                ('opprettet_av', models.ForeignKey(blank=True, help_text='Bruker som opprettet aktiviteten', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lag', models.ForeignKey(help_text='Lokallaget som eier denne aktiviteten', on_delete=django.db.models.deletion.CASCADE, related_name='aktiviteter', to='lag.lokallag')),
            ],
            options={
                'ordering': ['-dato', '-opprettet'],
            },
        ),
    ]
