# Generated by Django 5.2.7 on 2025-12-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0004_lokallag_aktivitet'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisasjon',
            name='forside_ingress',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='organisasjon',
            name='forside_tekst',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisasjon',
            name='forside_tittel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organisasjon',
            name='subdomene',
            field=models.SlugField(blank=True, help_text='f.eks. rakkestad (gir rakkestad.u3a.no)', max_length=63, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organisasjon',
            name='lenke_status',
            field=models.CharField(choices=[('active', 'active'), ('down', 'down'), ('unknown', 'unknown')], default='unknown', max_length=10, verbose_name='Lenkestatus'),
        ),
    ]
