# Generated by Django 5.2.7 on 2025-12-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0005_organisasjon_forside_ingress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisasjon',
            name='forside_bilde',
            field=models.ImageField(blank=True, null=True, upload_to='lokallag/forside/', verbose_name='Forsidebilde'),
        ),
    ]
