# Generated by Django 5.2.7 on 2026-01-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0006_organisasjon_forside_bilde'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoved_epost', models.EmailField(default='u3a@u3a.no', help_text='Brukes i footer på hovedsiden (u3a.no). Lokallag bruker sin egen e-post.', max_length=254, verbose_name='Hoved e-post (u3a.no)')),
                ('sist_endret', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SiteConfig',
                'verbose_name_plural': 'SiteConfig',
            },
        ),
    ]
