# Generated by Django 5.2.7 on 2026-01-02 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0007_siteconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisasjon',
            name='redaktorer',
            field=models.ManyToManyField(blank=True, help_text='Brukere som kan redigere denne organisasjonen i admin.', related_name='redaktor_for_organisasjoner', to=settings.AUTH_USER_MODEL),
        ),
    ]
