# Generated by Django 5.2.7 on 2026-01-02 21:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0008_organisasjon_redaktorer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitet',
            name='organisasjon',
            field=models.ForeignKey(blank=True, help_text='Organisasjonen (lokallaget) som eier aktiviteten', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktiviteter', to='lag.organisasjon'),
        ),
        migrations.AlterField(
            model_name='aktivitet',
            name='beskrivelse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aktivitet',
            name='kortinfo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='aktivitet',
            name='lag',
            field=models.ForeignKey(help_text='(DEPRECATED) Bruk organisasjon-feltet i stedet', on_delete=django.db.models.deletion.CASCADE, related_name='aktiviteter', to='lag.lokallag'),
        ),
        migrations.AlterField(
            model_name='aktivitet',
            name='opprettet_av',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aktivitet',
            name='publisert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aktivitet',
            name='slug',
            field=models.SlugField(max_length=220),
        ),
        migrations.AlterField(
            model_name='aktivitet',
            name='sted',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='organisasjon',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisasjon',
            name='breddegrad',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='organisasjon',
            name='epost',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organisasjon',
            name='kilde',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisasjon',
            name='lengdegrad',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='organisasjon',
            name='nettside',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisasjon',
            name='opprettet',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organisasjon',
            name='sist_endret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='organisasjon',
            name='status',
            field=models.CharField(choices=[('Aktiv', 'Aktiv'), ('Ukjent', 'Ukjent'), ('Passiv', 'Passiv')], default='Ukjent', max_length=10),
        ),
        migrations.AlterField(
            model_name='organisasjon',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hoved_epost',
            field=models.EmailField(default='u3a@u3a.no', max_length=254, verbose_name='Hoved e-post (u3a.no)'),
        ),
    ]
