# Generated by Django 5.2.7 on 2026-01-02 21:50
from django.db import migrations


def forwards(apps, schema_editor):
    Aktivitet = apps.get_model("lag", "Aktivitet")
    Lokallag = apps.get_model("lag", "Lokallag")
    Organisasjon = apps.get_model("lag", "Organisasjon")

    # Map: subdomene -> org_id
    org_by_sub = {}
    for o in Organisasjon.objects.all():
        if o.subdomene:
            org_by_sub[o.subdomene.strip().lower()] = o.id

    # Map: navn -> org_id (fallback)
    org_by_name = {}
    for o in Organisasjon.objects.all():
        if o.organisasjon:
            org_by_name[o.organisasjon.strip().lower()] = o.id

    # Flytt data
    qs = Aktivitet.objects.filter(organisasjon__isnull=True)
    for a in qs:
        org_id = None

        if a.lag_id:
            try:
                l = Lokallag.objects.get(id=a.lag_id)
            except Lokallag.DoesNotExist:
                l = None

            if l:
                slug = (l.slug or "").strip().lower()
                navn = (l.navn or "").strip().lower()

                if slug and slug in org_by_sub:
                    org_id = org_by_sub[slug]
                elif navn and navn in org_by_name:
                    org_id = org_by_name[navn]

        if org_id:
            a.organisasjon_id = org_id
            a.save(update_fields=["organisasjon"])


def backwards(apps, schema_editor):
    # ingen automatisk rollback
    pass


class Migration(migrations.Migration):

    dependencies = [
        # <-- BYTT denne til din forrige migrering i lag-appen hvis nødvendig
        ('lag', '0009_aktivitet_organisasjon_alter_aktivitet_beskrivelse_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

