# Generated by Django 5.2.7 on 2026-01-02 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0010_aktivitet_sett_organisasjon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitet',
            name='lag',
            field=models.ForeignKey(blank=True, help_text='(DEPRECATED) Bruk organisasjon-feltet i stedet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktiviteter', to='lag.lokallag'),
        ),
    ]
