# Generated by Django 5.2.7 on 2026-03-19 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0011_alter_aktivitet_lag'),
    ]

    operations = [
        migrations.CreateModel(
            name='LagRolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100, unique=True)),
                ('beskrivelse', models.CharField(blank=True, max_length=255, null=True)),
                ('opprettet', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Lagrolle',
                'verbose_name_plural': 'Lagroller',
                'ordering': ['navn'],
            },
        ),
        migrations.CreateModel(
            name='LagUtvalg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100, unique=True)),
                ('beskrivelse', models.CharField(blank=True, max_length=255, null=True)),
                ('opprettet', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Lagutvalg',
                'verbose_name_plural': 'Lagutvalg',
                'ordering': ['navn'],
            },
        ),
        migrations.CreateModel(
            name='LagMedlem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(max_length=100)),
                ('etternavn', models.CharField(max_length=100)),
                ('epost', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('postnummer', models.CharField(blank=True, max_length=10, null=True)),
                ('poststed', models.CharField(blank=True, max_length=100, null=True)),
                ('fodselsdato', models.DateField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('opprettet', models.DateTimeField(default=django.utils.timezone.now)),
                ('sist_endret', models.DateTimeField(auto_now=True)),
                ('organisasjon', models.ForeignKey(help_text='Lokallaget som eier medlemmet', on_delete=django.db.models.deletion.CASCADE, related_name='medlemmer', to='lag.organisasjon')),
            ],
            options={
                'verbose_name': 'Lagmedlem',
                'verbose_name_plural': 'Lagmedlemmer',
                'ordering': ['etternavn', 'fornavn'],
            },
        ),
        migrations.CreateModel(
            name='LagMedlemVerv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fra_dato', models.DateField(blank=True, null=True)),
                ('til_dato', models.DateField(blank=True, null=True)),
                ('valgt_dato', models.DateField(blank=True, null=True)),
                ('valgt_av', models.CharField(blank=True, max_length=100, null=True)),
                ('merknad', models.CharField(blank=True, max_length=255, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('opprettet', models.DateTimeField(default=django.utils.timezone.now)),
                ('sist_endret', models.DateTimeField(auto_now=True)),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verv', to='lag.lagmedlem')),
                ('organisasjon', models.ForeignKey(help_text='Lokallaget som eier vervet', on_delete=django.db.models.deletion.CASCADE, related_name='verv', to='lag.organisasjon')),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verv', to='lag.lagrolle')),
                ('utvalg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verv', to='lag.lagutvalg')),
            ],
            options={
                'verbose_name': 'Lagverv',
                'verbose_name_plural': 'Lagverv',
                'ordering': ['-aktiv', 'rolle__navn', 'medlem__etternavn'],
            },
        ),
    ]
