# Generated by Django 5.2.7 on 2026-05-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0012_lagrolle_lagutvalg_lagmedlem_lagmedlemverv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postnummer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postnummer', models.CharField(max_length=4, unique=True)),
                ('poststed', models.CharField(max_length=100)),
                ('kommune', models.CharField(blank=True, max_length=100, null=True)),
                ('fylke', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Postnummer',
                'verbose_name_plural': 'Postnummer',
                'ordering': ['postnummer'],
            },
        ),
    ]
