# Generated by Django 5.2.7 on 2026-05-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0013_postnummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lagmedlem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Registrert - ikke godkjent'), (2, 'Godkjent'), (6, 'Utmeldt'), (7, 'Suspendert'), (8, 'Permanent suspendert')], default=1),
        ),
    ]
