# Generated by Django 5.2.7 on 2026-05-04 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0014_lagmedlem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisasjon',
            name='opprettet',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrert dato'),
        ),
    ]
