# Generated by Django 5.2.7 on 2026-05-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0015_alter_organisasjon_opprettet'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisasjon',
            name='hjemmesidetype',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Enkel startside'), (2, '2 - Kalender og aktiviteter'), (3, '3 - Full lokallagsside')], default=1),
        ),
    ]
