# Generated by Django 5.2.7 on 2026-05-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0016_organisasjon_hjemmesidetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisasjon',
            name='orgnummer',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Organisasjonsnummer'),
        ),
    ]
