# Generated by Django 5.2.7 on 2026-05-09 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0017_organisasjon_orgnummer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=200)),
                ('dato', models.DateField()),
                ('starttid', models.TimeField()),
                ('sluttid', models.TimeField(blank=True, null=True)),
                ('sted', models.CharField(max_length=200)),
                ('foredragsholder', models.CharField(blank=True, max_length=200)),
                ('ingress', models.TextField(blank=True)),
                ('beskrivelse', models.TextField(blank=True)),
                ('publisert', models.BooleanField(default=True)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('sist_endret', models.DateTimeField(auto_now=True)),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangementer', to='lag.organisasjon')),
            ],
            options={
                'verbose_name': 'Arrangement',
                'verbose_name_plural': 'Arrangementer',
                'ordering': ['dato', 'starttid'],
            },
        ),
    ]
