# Generated by Django 5.2.7 on 2026-05-09 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0018_arrangement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nyhet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=200)),
                ('ingress', models.TextField(blank=True)),
                ('tekst', models.TextField(blank=True)),
                ('bilde', models.ImageField(blank=True, null=True, upload_to='nyheter/')),
                ('publisert', models.BooleanField(default=True)),
                ('publisert_dato', models.DateField(blank=True, null=True)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('sist_endret', models.DateTimeField(auto_now=True)),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nyheter', to='lag.organisasjon')),
            ],
            options={
                'verbose_name': 'Nyhet',
                'verbose_name_plural': 'Nyheter',
                'ordering': ['-publisert_dato', '-opprettet'],
            },
        ),
    ]
