# Generated by Django 5.2.7 on 2026-05-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0019_nyhet'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitet',
            name='bilde',
            field=models.ImageField(blank=True, null=True, upload_to='aktiviteter/bilder/'),
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='foredragsholder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='sluttid',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='starttid',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='vedlegg',
            field=models.FileField(blank=True, null=True, upload_to='aktiviteter/vedlegg/'),
        ),
    ]
