# Generated by Django 5.2.7 on 2026-05-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0020_aktivitet_bilde_aktivitet_foredragsholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisasjon',
            name='footer_tekst',
            field=models.TextField(blank=True, null=True),
        ),
    ]
