# Generated by Django 5.2.7 on 2026-05-17 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0021_organisasjon_footer_tekst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=200)),
                ('kategori', models.CharField(blank=True, max_length=100)),
                ('fil', models.FileField(upload_to='dokumenter/')),
                ('beskrivelse', models.TextField(blank=True)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('publisert', models.BooleanField(default=True)),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lag.organisasjon')),
            ],
        ),
    ]
