# Generated by Django 5.2.7 on 2026-05-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0022_dokument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='kategori',
            field=models.CharField(choices=[('referat', 'Referater'), ('arsmote', 'Årsmøte'), ('regnskap', 'Regnskap'), ('vedtekter', 'Vedtekter'), ('program', 'Program'), ('bilder', 'Bilder'), ('annet', 'Annet')], default='annet', max_length=50),
        ),
    ]
