# Generated by Django 5.2.7 on 2026-05-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0023_alter_dokument_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=200)),
                ('bilde', models.ImageField(upload_to='bilder/')),
                ('beskrivelse', models.TextField(blank=True)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('publisert', models.BooleanField(default=True)),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lag.organisasjon')),
            ],
        ),
    ]
