# Generated by Django 5.2.7 on 2026-05-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0024_bilde'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='er_styredokument',
            field=models.BooleanField(default=False),
        ),
    ]
