# Generated by Django 5.2.7 on 2026-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0027_dokument_opprettet_av_dokument_sist_endret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='kategori',
            field=models.CharField(choices=[('referat', 'Referater'), ('innkalling', 'Innkallinger'), ('arsmote', 'Årsmøte'), ('strategi', 'Strategi'), ('regnskap', 'Regnskap'), ('budsjett', 'Budsjett'), ('vedtekter', 'Vedtekter'), ('kontrakt', 'Kontrakter'), ('soknad', 'Søknader'), ('program', 'Program'), ('presentasjon', 'Presentasjoner'), ('bilder', 'Bilder'), ('annet', 'Annet')], default='annet', max_length=50),
        ),
    ]
