# Generated by Django 5.2.7 on 2026-05-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0028_alter_dokument_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medlemsgruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('aktiv', models.BooleanField(default=True)),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medlemsgrupper', to='lag.organisasjon')),
            ],
            options={
                'ordering': ['navn'],
                'unique_together': {('organisasjon', 'navn')},
            },
        ),
        migrations.AddField(
            model_name='lagmedlem',
            name='gruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medlemmer', to='lag.medlemsgruppe'),
        ),
    ]
