# Generated by Django 5.2.7 on 2026-05-23 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0029_medlemsgruppe_lagmedlem_gruppe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLeverandor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(blank=True, max_length=100)),
                ('api_url', models.CharField(blank=True, max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('avsender', models.CharField(blank=True, max_length=50)),
                ('aktiv', models.BooleanField(default=False)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('sist_endret', models.DateTimeField(auto_now=True)),
                ('organisasjon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_leverandor', to='lag.organisasjon')),
            ],
        ),
        migrations.CreateModel(
            name='SmsLogg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('melding', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Kladd'), (2, 'Test'), (3, 'Sendt'), (4, 'Feil')], default=1)),
                ('leverandor_svar', models.TextField(blank=True)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('sendt_tid', models.DateTimeField(blank=True, null=True)),
                ('medlem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logger', to='lag.lagmedlem')),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logger', to='lag.organisasjon')),
            ],
        ),
    ]
