# Generated by Django 5.2.7 on 2026-05-23 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0030_smsleverandor_smslogg'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsUtsending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melding', models.TextField()),
                ('mottakertekst', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Kladd - ikke sendt'), (2, 'Klar til sending'), (3, 'Sendt'), (4, 'Feil')], default=1)),
                ('antall_mottakere', models.IntegerField(default=0)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('sist_endret', models.DateTimeField(auto_now=True)),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_utsendinger', to='lag.organisasjon')),
            ],
        ),
        migrations.AddField(
            model_name='smslogg',
            name='utsending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mottakere', to='lag.smsutsending'),
        ),
    ]
