# Generated by Django 5.2.7 on 2026-05-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0031_smsutsending_smslogg_utsending'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsleverandor',
            name='testmodus',
            field=models.BooleanField(default=True, help_text='Når aktivert sendes ingen ekte SMS.'),
        ),
    ]
