# Generated by Django 5.2.7 on 2026-05-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0032_smsleverandor_testmodus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsutsending',
            name='status',
            field=models.IntegerField(choices=[(1, 'Kladd - ikke sendt'), (2, 'Klar til sending'), (3, 'Sendt'), (4, 'Feil'), (5, 'Test - ikke sendt eksternt')], default=1),
        ),
    ]
