# Generated by Django 5.2.7 on 2026-06-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0034_lagmedlem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidevisning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateField()),
                ('host', models.CharField(max_length=255)),
                ('sti', models.CharField(max_length=500)),
                ('antall', models.PositiveIntegerField(default=0)),
                ('sist_besokt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sidevisning',
                'verbose_name_plural': 'Sidevisninger',
                'ordering': ['-dato', '-antall'],
                'unique_together': {('dato', 'host', 'sti')},
            },
        ),
    ]
