# Generated by Django 5.2.7 on 2026-06-14 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0035_sidevisning'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitet',
            name='pamelding_aktiv',
            field=models.BooleanField(default=False, verbose_name='Påmelding aktiv'),
        ),
        migrations.CreateModel(
            name='AktivitetPamelding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('epost', models.EmailField(max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('aktivitet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pameldinger', to='lag.aktivitet')),
            ],
            options={
                'ordering': ['opprettet'],
            },
        ),
    ]
