# Generated by Django 5.2.7 on 2026-06-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0036_aktivitet_pamelding_aktiv_aktivitetpamelding'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitet',
            name='maks_antall',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maks antall deltakere'),
        ),
    ]
