# Generated by Django 5.2.7 on 2026-06-30 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0037_aktivitet_maks_antall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lagmedlem',
            name='familiemedlem',
            field=models.BooleanField(default=False, help_text='Markerer om medlemmet er familiemedlem.'),
        ),
        migrations.AddField(
            model_name='lagmedlem',
            name='hovedmedlem',
            field=models.ForeignKey(blank=True, help_text='Hovedmedlem dersom dette medlemmet er del av en familie.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familiemedlemmer', to='lag.lagmedlem'),
        ),
        migrations.AddField(
            model_name='lagmedlem',
            name='medlemsnummer',
            field=models.PositiveIntegerField(blank=True, help_text='Medlemsnummer. Brukes også som kontonummer i regnskapet.', null=True),
        ),
        migrations.AddConstraint(
            model_name='lagmedlem',
            constraint=models.UniqueConstraint(fields=('organisasjon', 'medlemsnummer'), name='unik_medlemsnummer_per_organisasjon'),
        ),
    ]
