# Generated by Django 5.2.7 on 2026-05-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('audience', models.CharField(blank=True, max_length=200)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='school/courses/')),
                ('is_published', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('intro', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('reflection_prompt', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='school.course')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'unique_together': {('course', 'slug')},
            },
        ),
    ]
