# Generated by Django 5.2.7 on 2025-11-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_column', models.TextField(blank=True)),
                ('center_column', models.TextField(blank=True)),
                ('right_column', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Forsideinnhold',
                'verbose_name_plural': 'Forsideinnhold',
            },
        ),
    ]
