# Generated by Django 5.2.7 on 2026-06-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lag', '0037_aktivitet_maks_antall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regnskapsaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aar', models.PositiveIntegerField()),
                ('navn', models.CharField(blank=True, max_length=50)),
                ('fra_dato', models.DateField()),
                ('til_dato', models.DateField()),
                ('aktiv', models.BooleanField(default=True)),
                ('avsluttet', models.BooleanField(default=False)),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regnskapsaar', to='lag.organisasjon')),
            ],
            options={
                'verbose_name': 'Regnskapsår',
                'verbose_name_plural': 'Regnskapsår',
                'ordering': ['-aar'],
                'unique_together': {('organisasjon', 'aar')},
            },
        ),
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontonummer', models.PositiveSmallIntegerField()),
                ('kontonavn', models.CharField(max_length=100)),
                ('styrekode', models.CharField(max_length=4)),
                ('samlekonto', models.BooleanField(default=False)),
                ('krever_avdeling', models.BooleanField(default=False)),
                ('krever_prosjekt', models.BooleanField(default=False)),
                ('aktiv', models.BooleanField(default=True)),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontoer', to='lag.organisasjon')),
            ],
            options={
                'verbose_name': 'Konto',
                'verbose_name_plural': 'Kontoplan',
                'ordering': ['kontonummer'],
                'unique_together': {('organisasjon', 'kontonummer')},
            },
        ),
        migrations.CreateModel(
            name='Bilagsserie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=5)),
                ('navn', models.CharField(max_length=100)),
                ('neste_nummer', models.PositiveIntegerField(default=1)),
                ('standard_konto', models.PositiveIntegerField(blank=True, null=True)),
                ('standard_fortegn', models.CharField(blank=True, choices=[('+', 'Debet'), ('-', 'Kredit')], max_length=1)),
                ('aktiv', models.BooleanField(default=True)),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilagsserier', to='lag.organisasjon')),
                ('regnskapsaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilagsserier', to='regnskap.regnskapsaar')),
            ],
            options={
                'verbose_name': 'Bilagsserie',
                'verbose_name_plural': 'Bilagsserier',
                'ordering': ['kode'],
                'unique_together': {('organisasjon', 'regnskapsaar', 'kode')},
            },
        ),
        migrations.CreateModel(
            name='Regnskapsperiode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodenummer', models.PositiveSmallIntegerField()),
                ('fra_dato', models.DateField()),
                ('til_dato', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Åpen'), (0, 'Avsluttet')], default=1)),
                ('regnskapsaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perioder', to='regnskap.regnskapsaar')),
            ],
            options={
                'verbose_name': 'Regnskapsperiode',
                'verbose_name_plural': 'Regnskapsperioder',
                'ordering': ['periodenummer'],
                'unique_together': {('regnskapsaar', 'periodenummer')},
            },
        ),
    ]
