# Generated by Django 5.2.7 on 2026-06-20 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0037_aktivitet_maks_antall'),
        ('regnskap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avdeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avdelingsnummer', models.PositiveIntegerField()),
                ('navn', models.CharField(max_length=100)),
                ('fra_dato', models.DateField(blank=True, null=True)),
                ('til_dato', models.DateField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('ansvarlig_medlem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lag.lagmedlem')),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avdelinger', to='lag.organisasjon')),
            ],
            options={
                'ordering': ['avdelingsnummer'],
                'unique_together': {('organisasjon', 'avdelingsnummer')},
            },
        ),
        migrations.CreateModel(
            name='Prosjekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prosjektnummer', models.PositiveIntegerField()),
                ('navn', models.CharField(max_length=100)),
                ('beskrivelse', models.TextField(blank=True)),
                ('fra_dato', models.DateField(blank=True, null=True)),
                ('til_dato', models.DateField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('ansvarlig_medlem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lag.lagmedlem')),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosjekter', to='lag.organisasjon')),
            ],
            options={
                'ordering': ['prosjektnummer'],
                'unique_together': {('organisasjon', 'prosjektnummer')},
            },
        ),
    ]
