# Generated by Django 5.2.7 on 2026-06-20 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0037_aktivitet_maks_antall'),
        ('regnskap', '0002_avdeling_prosjekt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReskontroKonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontonummer', models.PositiveIntegerField()),
                ('navn', models.CharField(max_length=100)),
                ('reskontrotype', models.CharField(choices=[('MEDLEM', 'Medlem'), ('KUNDE', 'Kunde'), ('LEVERANDOR', 'Leverandør')], default='MEDLEM', max_length=20)),
                ('aktiv', models.BooleanField(default=True)),
                ('medlem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reskontro_kontoer', to='lag.lagmedlem')),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reskontro_kontoer', to='lag.organisasjon')),
                ('samlekonto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reskontro_kontoer', to='regnskap.konto')),
            ],
            options={
                'verbose_name': 'Reskontrokonto',
                'verbose_name_plural': 'Reskontrokontoer',
                'ordering': ['kontonummer'],
                'unique_together': {('organisasjon', 'kontonummer')},
            },
        ),
    ]
