# Generated by Django 5.2.7 on 2026-06-20 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0037_aktivitet_maks_antall'),
        ('regnskap', '0003_reskontrokonto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilagsnummer', models.PositiveIntegerField()),
                ('bilagsdato', models.DateField()),
                ('foringsdato', models.DateField()),
                ('h_status', models.IntegerField(default=1)),
                ('a_status', models.IntegerField(default=1)),
                ('p_status', models.IntegerField(default=1)),
                ('bilagstekst', models.CharField(max_length=200)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('sist_endret', models.DateTimeField(auto_now=True)),
                ('bilagsserie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bilag', to='regnskap.bilagsserie')),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilag', to='lag.organisasjon')),
                ('registrert_av', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrerte_bilag', to=settings.AUTH_USER_MODEL)),
                ('regnskapsaar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bilag', to='regnskap.regnskapsaar')),
            ],
            options={
                'verbose_name': 'Bilag',
                'verbose_name_plural': 'Bilag',
                'ordering': ['regnskapsaar', 'bilagsserie', 'bilagsnummer'],
                'unique_together': {('regnskapsaar', 'bilagsserie', 'bilagsnummer')},
            },
        ),
        migrations.CreateModel(
            name='Momskode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('navn', models.CharField(max_length=100)),
                ('sats', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aktiv', models.BooleanField(default=True)),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momskoder', to='lag.organisasjon')),
            ],
            options={
                'verbose_name': 'Momskode',
                'verbose_name_plural': 'Momskoder',
                'ordering': ['kode'],
                'unique_together': {('organisasjon', 'kode')},
            },
        ),
        migrations.CreateModel(
            name='Bilagslinje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linjenummer', models.PositiveIntegerField()),
                ('kontonummer', models.PositiveIntegerField()),
                ('linjetekst', models.CharField(blank=True, max_length=200)),
                ('belop', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avdeling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bilagslinjer', to='regnskap.avdeling')),
                ('bilag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linjer', to='regnskap.bilag')),
                ('prosjekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bilagslinjer', to='regnskap.prosjekt')),
                ('momskode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bilagslinjer', to='regnskap.momskode')),
            ],
            options={
                'verbose_name': 'Bilagslinje',
                'verbose_name_plural': 'Bilagslinjer',
                'ordering': ['bilag', 'linjenummer'],
                'unique_together': {('bilag', 'linjenummer')},
            },
        ),
    ]
