# Generated by Django 5.2.7 on 2026-06-20 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0037_aktivitet_maks_antall'),
        ('regnskap', '0004_bilag_momskode_bilagslinje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tidspunkt', models.DateTimeField(auto_now_add=True)),
                ('modul', models.CharField(blank=True, max_length=50)),
                ('tabellnavn', models.CharField(max_length=100)),
                ('post_id', models.CharField(blank=True, max_length=50)),
                ('handling', models.CharField(max_length=50)),
                ('felt_navn', models.CharField(blank=True, max_length=100)),
                ('gammel_verdi', models.TextField(blank=True)),
                ('ny_verdi', models.TextField(blank=True)),
                ('kommentar', models.TextField(blank=True)),
                ('bruker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systemlogger', to=settings.AUTH_USER_MODEL)),
                ('organisasjon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systemlogger', to='lag.organisasjon')),
            ],
            options={
                'verbose_name': 'Systemlogg',
                'verbose_name_plural': 'Systemlogger',
                'ordering': ['-tidspunkt'],
            },
        ),
    ]
