# Generated by Django 5.2.7 on 2026-06-21 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0037_aktivitet_maks_antall'),
        ('regnskap', '0005_systemlogg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Styrekode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=4)),
                ('fortekst', models.CharField(max_length=100)),
                ('sumtekst', models.CharField(max_length=100)),
                ('aktiv', models.BooleanField(default=True)),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regnskap_styrekoder', to='lag.organisasjon')),
            ],
            options={
                'verbose_name': 'Styrekode',
                'verbose_name_plural': 'Styrekoder',
                'ordering': ['kode'],
                'unique_together': {('organisasjon', 'kode')},
            },
        ),
    ]
