# Generated by Django 5.2.7 on 2026-06-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regnskap', '0006_styrekode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilagsserie',
            name='standard_tekst',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
