# Generated by Django 5.2.7 on 2026-06-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0037_aktivitet_maks_antall'),
        ('regnskap', '0007_bilagsserie_standard_tekst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regnskapsoppsett',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=150)),
                ('adresse', models.CharField(blank=True, max_length=150)),
                ('postnummer', models.CharField(blank=True, max_length=10)),
                ('poststed', models.CharField(blank=True, max_length=80)),
                ('bankkonto', models.CharField(blank=True, max_length=30)),
                ('organisasjonsnummer', models.CharField(blank=True, max_length=20)),
                ('mva_pliktig', models.BooleanField(default=False)),
                ('hovedbok_fra', models.PositiveIntegerField(default=100)),
                ('hovedbok_til', models.PositiveIntegerField(default=999)),
                ('leverandor_fra', models.PositiveIntegerField(default=1000)),
                ('leverandor_til', models.PositiveIntegerField(default=1999)),
                ('medlem_fra', models.PositiveIntegerField(default=2000)),
                ('medlem_til', models.PositiveIntegerField(default=2999)),
                ('kunde_fra', models.PositiveIntegerField(default=3000)),
                ('kunde_til', models.PositiveIntegerField(default=3999)),
                ('regnskapsaar_fra', models.PositiveIntegerField(default=2020)),
                ('regnskapsaar_til', models.PositiveIntegerField(default=2099)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='regnskap/logo/')),
                ('organisasjon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regnskapsoppsett', to='lag.organisasjon')),
            ],
            options={
                'verbose_name': 'Regnskapsoppsett',
                'verbose_name_plural': 'Regnskapsoppsett',
            },
        ),
    ]
