# Generated by Django 5.2.7 on 2026-06-27 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regnskap', '0008_regnskapsoppsett'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilag',
            name='tilbakeforing_av',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tilbakeforinger', to='regnskap.bilag'),
        ),
    ]
