# Generated by Django 5.2.7 on 2026-06-28 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0037_aktivitet_maks_antall'),
        ('regnskap', '0009_bilag_tilbakeforing_av'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamlekontoOppsett',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(choices=[('LEVERANDOR', 'Leverandørsamlekonto'), ('KUNDE', 'Kundesamlekonto'), ('MEDLEM', 'Medlemssamlekonto')], max_length=30)),
                ('navn', models.CharField(max_length=100)),
                ('aktiv', models.BooleanField(default=True)),
                ('konto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samlekonto_oppsett', to='regnskap.konto')),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samlekonto_oppsett', to='lag.organisasjon')),
            ],
            options={
                'verbose_name': 'Samlekonto-oppsett',
                'verbose_name_plural': 'Samlekonto-oppsett',
                'unique_together': {('organisasjon', 'kode')},
            },
        ),
    ]
