# Generated by Django 5.2.7 on 2026-06-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regnskap', '0010_samlekontooppsett'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReskontroKonto',
        ),
    ]
