# Generated by Django 5.2.7 on 2026-06-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regnskap', '0011_delete_reskontrokonto'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlekontooppsett',
            name='neste_nummer',
            field=models.PositiveIntegerField(default=10000, verbose_name='Neste nummer'),
        ),
    ]
