# Generated by Django 5.2.7 on 2026-06-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regnskap', '0012_samlekontooppsett_neste_nummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlekontooppsett',
            name='avskrivningsregel_notat',
            field=models.TextField(blank=True, help_text='Foreløpig notatfelt. Egen avskrivningsregel kommer senere.', verbose_name='Avskrivningsregel / skattemessig notat'),
        ),
        migrations.AlterField(
            model_name='samlekontooppsett',
            name='kode',
            field=models.CharField(choices=[('LEVERANDOR', 'Leverandørsamlekonto'), ('KUNDE', 'Kundesamlekonto'), ('MEDLEM', 'Medlemssamlekonto'), ('BIL', 'Bilsamlekonto'), ('EIENDEL', 'Eiendelssamlekonto'), ('ANNET', 'Annen samlekonto')], max_length=30),
        ),
    ]
