# Generated by Django 5.2.7 on 2026-06-29 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0037_aktivitet_maks_antall'),
        ('regnskap', '0013_samlekontooppsett_avskrivningsregel_notat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamlekontoDefinisjon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='F.eks. KUNDE, LEVERANDOR, MEDLEM, BIL, HYTTE', max_length=30)),
                ('navn', models.CharField(help_text='F.eks. Kunder, Leverandører, Medlemmer, Biler', max_length=100)),
                ('beskrivelse', models.TextField(blank=True)),
                ('bruker_nummer', models.BooleanField(default=True, help_text='Om denne samlekonto-typen bruker løpende nummer.')),
                ('aktiv', models.BooleanField(default=True)),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samlekonto_definisjoner', to='lag.organisasjon')),
            ],
            options={
                'verbose_name': 'Samlekonto-definisjon',
                'verbose_name_plural': 'Samlekonto-definisjoner',
                'ordering': ('kode',),
                'unique_together': {('organisasjon', 'kode')},
            },
        ),
    ]
