# Generated by Django 5.2.7 on 2026-06-29 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0037_aktivitet_maks_antall'),
        ('regnskap', '0014_samlekontodefinisjon'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlekontooppsett',
            name='definisjon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oppsett', to='regnskap.samlekontodefinisjon'),
        ),
        migrations.RemoveField(
            model_name='samlekontooppsett',
            name='kode',
        ),
        migrations.RemoveField(
            model_name='samlekontooppsett',
            name='navn',
        ),
        migrations.AlterUniqueTogether(
            name='samlekontooppsett',
            unique_together={('organisasjon', 'definisjon')},
        ),
    ]
