# Generated by Django 5.2.7 on 2026-06-29 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regnskap', '0015_alter_samlekontooppsett_unique_together_and_more'),
    ]

    operations = [

        migrations.CreateModel(
            name='SamlekontoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('neste_nummer', models.PositiveIntegerField(default=1)),
                ('bruker_lopende_nummer', models.BooleanField(default=True)),
                ('beskrivelse', models.TextField(blank=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('hovedbokskonto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='samlekontotype', to='regnskap.konto', verbose_name='Hovedbokskonto')),
            ],
        ),
        migrations.DeleteModel(
            name='SamlekontoDefinisjon',
        ),
        migrations.DeleteModel(
            name='SamlekontoOppsett',
        ),
    ]
