# Generated by Django 5.2.7 on 2026-06-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regnskap', '0016_remove_samlekontooppsett_definisjon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlekontotype',
            name='nummer_fra',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='samlekontotype',
            name='nummer_til',
            field=models.PositiveIntegerField(default=999999),
        ),
        migrations.AddField(
            model_name='samlekontotype',
            name='registertype',
            field=models.CharField(choices=[('LEVERANDOR', 'Leverandører'), ('KUNDE', 'Kunder'), ('MEDLEM', 'Medlemmer'), ('BIL', 'Biler'), ('ANNET', 'Annet')], default='ANNET', max_length=30),
        ),
    ]
