# Generated by Django 5.2.7 on 2026-06-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regnskap', '0017_samlekontotype_nummer_fra_samlekontotype_nummer_til_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samlekontotype',
            name='registertype',
        ),
    ]
