# Generated by Django 5.2.7 on 2026-06-30 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lag', '0037_aktivitet_maks_antall'),
        ('regnskap', '0018_remove_samlekontotype_registertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leverandor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=150)),
                ('orgnummer', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=150)),
                ('postnummer', models.CharField(blank=True, max_length=20)),
                ('poststed', models.CharField(blank=True, max_length=100)),
                ('land', models.CharField(blank=True, default='Norge', max_length=100)),
                ('kontaktperson', models.CharField(blank=True, max_length=100)),
                ('epost', models.EmailField(blank=True, max_length=254)),
                ('url', models.URLField(blank=True, verbose_name='Nettside')),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('bankkonto', models.CharField(blank=True, max_length=30)),
                ('iban', models.CharField(blank=True, max_length=40)),
                ('bic', models.CharField(blank=True, max_length=20, verbose_name='BIC/SWIFT')),
                ('aktiv', models.BooleanField(default=True)),
                ('notat', models.TextField(blank=True)),
                ('konto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='leverandor', to='regnskap.konto')),
                ('organisasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leverandorer', to='lag.organisasjon')),
            ],
            options={
                'verbose_name': 'Leverandør',
                'verbose_name_plural': 'Leverandører',
                'ordering': ['navn'],
            },
        ),
    ]
